// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftballManager.Api.Data;

#nullable disable

namespace SoftballManager.Api.Data.Migrations
{
    [DbContext(typeof(SoftballDbContext))]
    [Migration("20260928025657_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SoftballManager.Api.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AwayTeamId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OpponentName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "AwayTeamId");

                    b.HasIndex("SeasonId", "HomeTeamId");

                    b.ToTable("games", null, t =>
                        {
                            t.HasCheckConstraint("ck_games_opponent", "((AwayTeamId IS NOT NULL AND OpponentName IS NULL) OR (AwayTeamId IS NULL AND OpponentName IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("SoftballManager.Api.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("SoftballManager.Api.Domain.PlayerSeasonPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTimeOffset?>("PaidAtUtc")
                        .HasColumnType("datetime");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("PlayerId", "SeasonId")
                        .IsUnique();

                    b.ToTable("player_season_payments", (string)null);
                });

            modelBuilder.Entity("SoftballManager.Api.Domain.RosterEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId", "TeamId", "PlayerId")
                        .IsUnique();

                    b.ToTable("roster_entries", (string)null);
                });

            modelBuilder.Entity("SoftballManager.Api.Domain.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("SoftballManager.Api.Domain.SeasonTeam", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.HasKey("SeasonId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("season_teams", (string)null);
                });

            modelBuilder.Entity("SoftballManager.Api.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("SoftballManager.Api.Domain.Game", b =>
                {
                    b.HasOne("SoftballManager.Api.Domain.SeasonTeam", null)
                        .WithMany()
                        .HasForeignKey("SeasonId", "AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SoftballManager.Api.Domain.SeasonTeam", null)
                        .WithMany()
                        .HasForeignKey("SeasonId", "HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SoftballManager.Api.Domain.PlayerSeasonPayment", b =>
                {
                    b.HasOne("SoftballManager.Api.Domain.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftballManager.Api.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("SoftballManager.Api.Domain.RosterEntry", b =>
                {
                    b.HasOne("SoftballManager.Api.Domain.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftballManager.Api.Domain.SeasonTeam", null)
                        .WithMany()
                        .HasForeignKey("SeasonId", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SoftballManager.Api.Domain.SeasonTeam", b =>
                {
                    b.HasOne("SoftballManager.Api.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftballManager.Api.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
